// Generated by CoffeeScript 1.9.2
(function() {
  var ConsoleInterface, Game, game;

  Game = require('./game');

  ConsoleInterface = require('./interfaces/console_interface');

  game = new Game();

  game.addInterface(ConsoleInterface);

  game.startGame();

}).call(this);
