// Generated by CoffeeScript 1.9.2
(function() {
  var Game, RpiInterface, game;

  Game = require('./game');

  RpiInterface = require('./interfaces/rpi_interface');

  game = new Game();

  game.addInterface(new RpiInterface());

  game.startGame();

}).call(this);

//# sourceMappingURL=runner.js.map
